image: docker

stages:
  - lint
  - build
  - deploy
  
lint:
  image: node:10.15-alpine
  stage: lint
  cache:
    paths:
      - node_modules
  script:
    - npm install --registry=https://npm.gisauto.ru
    - npm run lint

build_development:
  stage: build
  image: docker:stable
    
  before_script:
    - docker info

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:develop .
    - docker push $CI_REGISTRY_IMAGE:develop


