image: node:10.15-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test_async:
  script:
    - npm run install
    - node ./specs/start.js ./specs/async.spec.js

build:
  script:
    - npm run build
